name: GeoDjango Tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  SpatiaLite:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version:
          - '3.12'
          - '3.13'
    name: Ubuntu, SpatiaLite, Python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create SpatiaLite settings file
        run: mv ./.github/workflows/data/test_spatialite.py.tpl ./tests/test_spatialite.py
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: 'geodjango'
          environment-file: './.github/workflows/data/spatialite-environment.yml'
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Install Django and test dependencies
        run: |
          python -m pip install  -e .
      - name: runtests
        run: python -Wall tests/runtests.py -v2  --settings=test_spatialite gis_tests
