name: GeoDjango Tests (Conda Matrix)

on:
  pull_request:
    types: [labeled, synchronize, opened, reopened]
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  postgis-conda:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'geodjango')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - conda-environment-file: ".github/workflows/data/conda/geolibs-pg15.yml"
            pg_major: "15"
          - conda-environment-file: ".github/workflows/data/conda/geolibs-pg16.yml"
            pg_major: "16"
          - conda-environment-file: ".github/workflows/data/conda/geolibs-pg17.yml"
            pg_major: "17"
          - conda-environment-file: ".github/workflows/data/conda/geolibs-pg18.yml"
            pg_major: "18"
    name: Conda PostGIS / PG${{ matrix.pg_major }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Miniforge
        # Pinned to v3.2.0.
        uses: conda-incubator/setup-miniconda@835234971496cad1653abb28a638a281cf32541f
        with:
          miniforge-version: "24.1.2-0"
          activate-environment: geodjango
          environment-file: ${{ matrix.conda-environment-file }}
          use-mamba: true
          channel-priority: strict

      - name: Install and upgrade packaging tools
        shell: bash -el {0}
        run: python -m pip install --upgrade pip wheel

      - name: Install Django test dependencies
        shell: bash -el {0}
        run: python -m pip install -r tests/requirements/py3.txt -r tests/requirements/postgres.txt -e .

      - name: Create PostgreSQL settings file
        run: mv ./.github/workflows/data/test_postgis.py.tpl ./tests/test_postgis.py

      - name: Initialize and start local PostgreSQL
        shell: bash -el {0}
        run: |
          initdb -D "$GITHUB_WORKSPACE/.tmp/postgis-pgdata" --username="user" --auth=trust
          pg_ctl -D "$GITHUB_WORKSPACE/.tmp/postgis-pgdata" -w start
          psql -U user -d postgres -c "CREATE EXTENSION IF NOT EXISTS postgis;"
          psql -U user -d postgres -c "SELECT PostGIS_full_version();"

      - name: Print geospatial versions
        shell: bash -el {0}
        run: |
          python -c "from django.contrib.gis import gdal, geos; print(f'GDAL: {gdal.gdal_version()}'); print(f'GEOS: {geos.geos_version()}')"

      - name: Run PostGIS tests
        shell: bash -el {0}
        run: python -Wall tests/runtests.py -v2 --settings=test_postgis
